import { test } from 'node:test';
import assert from 'node:assert/strict';
import { GuardedWallet } from '../../apps/web/src/wallet/provider.js';
import type { WalletReview, WalletTransaction, WalletIntent } from '@verdict/protocol';

const tx:WalletTransaction={chainId:'0x1',from:'0x1111111111111111111111111111111111111111',to:'0x2222222222222222222222222222222222222222',value:'0x1',data:'0x'};
const intent:WalletIntent={account:tx.from,chainId:tx.chainId,recipient:tx.to,maxValueWei:'1',maxTotalFeeWei:'1000000000000000',operation:'native_transfer'};
function review(status:WalletReview['status'],transaction:WalletTransaction=tx):WalletReview{return {schemaVersion:'wallet-review-v1',reviewId:'r1',clientRequestId:'c1',inputDigest:'0x'+'1'.repeat(64),transactionDigest:status==='ALLOWED'?'0x'+'2'.repeat(64):null,transaction,intent,preparedTransaction:status==='ALLOWED'?{...transaction,nonce:'0x1',gas:'0x5208',maxFeePerGas:'0x2',maxPriorityFeePerGas:'0x1'}:null,status,reason:status,createdAt:Date.now(),expiresAt:status==='ALLOWED'?Date.now()+60000:null,checks:[],events:[],reviewer:{modelId:'reviewer',source:'TEST_TRANSPORT',verdict:status==='ALLOWED'?'ALLOW':null},usage:{requests:1,inputTokens:1,outputTokens:1,cacheReadTokens:0,cacheWriteTokens:0,costUsd:null},broadcastStatus:'NOT_BROADCAST_BY_SERVER'};}
test('wallet does not call eth_sendTransaction until an allowed review is consumed',async()=>{
 let poll=0,sends=0,consumes=0;const provider={request:async({method}:{method:string;params?:unknown[]})=>{if(method==='eth_requestAccounts')return [tx.from];if(method==='eth_accounts')return [tx.from];if(method==='eth_chainId')return tx.chainId;if(method==='eth_sendTransaction'){sends++;return '0x'+'a'.repeat(64);}throw Error(method);}};
 const api=async(path:string,body?:unknown)=>{if(path==='/api/wallet/reviews')return review('QUEUED');if(path==='/api/wallet/reviews/r1')return ++poll<2?review('REVIEWING'):review('ALLOWED');if(path==='/api/wallet/reviews/r1/consume'){consumes++;return {reviewId:'r1',transaction:body && (body as any).transaction};}if(path.endsWith('/cancel'))return review('CANCELLED');throw Error(path);};
 const wallet=new GuardedWallet(api);await wallet.connect(provider);const hash=await wallet.reviewAndSend(tx,intent);assert.equal(hash,'0x'+'a'.repeat(64));assert.equal(sends,1);assert.equal(consumes,1);
});
test('wallet provider change invalidates review before consumption',async()=>{
 let chain='0x1',consumes=0,sends=0;const provider={request:async({method}:{method:string})=>{if(method==='eth_requestAccounts'||method==='eth_accounts')return [tx.from];if(method==='eth_chainId')return chain;if(method==='eth_sendTransaction'){sends++;return '0x'+'a'.repeat(64);}throw Error(method);}};
 let first=true;const api=async(path:string,body?:unknown)=>{if(path==='/api/wallet/reviews')return review('QUEUED');if(path==='/api/wallet/reviews/r1')return review('ALLOWED');if(path.endsWith('/consume')){consumes++;return {reviewId:'r1',transaction:(body as any).transaction};}if(path.endsWith('/cancel'))return review('CANCELLED');throw Error(path);};
 const wallet=new GuardedWallet(api);await wallet.connect(provider);const pending=wallet.review(tx,intent);chain='0x2';await assert.rejects(pending,/WALLET_CHANGED/);assert.equal(consumes,0);assert.equal(sends,0);void first;
});
test('blocked review never reaches wallet',async()=>{let sends=0;const provider={request:async({method}:{method:string})=>method==='eth_requestAccounts'||method==='eth_accounts'?[tx.from]:method==='eth_chainId'?tx.chainId:(sends++,'0x')};const api=async(path:string)=>path==='/api/wallet/reviews'?review('BLOCKED'):path.endsWith('/cancel')?review('CANCELLED'):review('BLOCKED');const wallet=new GuardedWallet(api);await wallet.connect(provider);await assert.rejects(wallet.reviewAndSend(tx,intent),/BLOCKED/);assert.equal(sends,0);});
